require: rubocop-rspec

AllCops:
  DisplayCopNames: true

  Exclude:
    - bin/update
    - bin/setup
    - bin/bundle
    - Guardfile

Metrics/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 3

Style/Documentation:
  Exclude:
    - db/migrate/*

RSpec/DescribeClass:
  Exclude:
    - spec/features/creating_article_spec.rb

RSpec/ExampleLength:
  Exclude:
  - spec/features/creating_article_spec.rb

Style/Documentation:
  Enabled: false